# Generated by Django 5.0.4 on 2024-04-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
